sudo: false

language: go

go:
  - 1.6

python:
  - 2.7
  - 3.5

script:
  - ./bootstrap.sh --plain_output

before_install:
  - ./.travis_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libunittest++-dev
      - binutils
      - clang
      - gcc-4.8
      - g++-4.8
      - unzip

install:
  - pip install --user cffi==1.8.2

git:
  depth: 3

cache:
  directories:
    - $HOME/protoc
    - $HOME/plz-cache
